# Generated by Django 5.0.4 on 2024-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
